### ISSUE TITLE
AWS Signature Version 2 Deprecation for Amazon S3

### ISSUE THREAD

**Issue by lemonkazi** [danharper/fuel-s3#3]
I got this notice from AWS.
AWS Signature Version 2 Deprecation for Amazon S3 .
I used your code in my app. is there do I have to change anything for this update?
or it's ok? 
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-sig2-deprecation

**Comment by kaysersoze** [comment]
@lemonkazi It looks like the S3 library that `fuel-s3` uses (https://github.com/tpyo/amazon-s3-php-class) has a pending pull request with AWS v4 signature support here: https://github.com/tpyo/amazon-s3-php-class/pull/128

Looking at that thread, it looks like there's a forked version by @svenbluege that supports v4 signatures here: https://github.com/svenbluege/amazon-s3-php-class

You will need to replace the code in `/classes/**` with the forked version, and you will probably want to manually split the forked library as has been done in this package, or modify the Autoloader.
